import type { EditorThemeClasses } from "lexical";

/**
 * Maps Lexical's built-in node/format classes onto the same `lb-*` class
 * names lightbook-prosemirror's `style.css` already defines, so both
 * packages can ship (and consumers can override) one shared stylesheet.
 */
export const lightbookTheme: EditorThemeClasses = {
  ltr: "lb-ltr",
  rtl: "lb-rtl",
  paragraph: "lb-paragraph",
  quote: "lb-blockquote",
  heading: {
    h1: "lb-heading-1",
    h2: "lb-heading-2",
    h3: "lb-heading-3",
    h4: "lb-heading-4",
  },
  list: {
    ul: "lb-list-bullet",
    ol: "lb-list-ordered",
    checklist: "lb-list-checkbox",
    listitem: "lb-list-item",
    listitemChecked: "lb-list-item-checked",
    listitemUnchecked: "lb-list-item-unchecked",
    nested: {
      listitem: "lb-list-item-nested",
    },
  },
  code: "lb-code-block",
  codeHighlight: {
    atrule: "lb-token-attr",
    attr: "lb-token-attr",
    boolean: "lb-token-boolean",
    builtin: "lb-token-builtin",
    cdata: "lb-token-comment",
    char: "lb-token-string",
    class: "lb-token-class",
    "class-name": "lb-token-class",
    comment: "lb-token-comment",
    constant: "lb-token-constant",
    deleted: "lb-token-deleted",
    doctype: "lb-token-comment",
    entity: "lb-token-operator",
    function: "lb-token-function",
    important: "lb-token-important",
    inserted: "lb-token-inserted",
    keyword: "lb-token-keyword",
    namespace: "lb-token-variable",
    number: "lb-token-number",
    operator: "lb-token-operator",
    prolog: "lb-token-comment",
    property: "lb-token-property",
    punctuation: "lb-token-punctuation",
    regex: "lb-token-variable",
    selector: "lb-token-selector",
    string: "lb-token-string",
    symbol: "lb-token-boolean",
    tag: "lb-token-tag",
    url: "lb-token-operator",
    variable: "lb-token-variable",
  },
  link: "lb-link",
  text: {
    bold: "lb-text-bold",
    italic: "lb-text-italic",
    underline: "lb-text-underline",
    strikethrough: "lb-text-strikethrough",
    underlineStrikethrough: "lb-text-underline-strikethrough",
    code: "lb-text-code",
    subscript: "lb-text-subscript",
    superscript: "lb-text-superscript",
    highlight: "lb-text-highlight",
  },
  mark: "lb-mark",
  markOverlap: "lb-mark-overlap",
  table: "lb-table",
  tableCell: "lb-table-cell",
  tableCellHeader: "lb-table-cell-header",
  tableRow: "lb-table-row",
  hr: "lb-hr",
};
